package aidetect_test

import (
	"testing"

	"github.com/dsablic/codemium/internal/aidetect"
	"github.com/dsablic/codemium/internal/model"
)

func TestDetectCoAuthorTrailer(t *testing.T) {
	tests := []struct {
		name    string
		author  string
		message string
		want    []model.AISignal
	}{
		{
			name:    "Claude co-author",
			message: "feat: add feature\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
			want:    []model.AISignal{model.SignalCoAuthor},
		},
		{
			name:    "Copilot co-author",
			message: "fix: bug\n\nCo-authored-by: Copilot <copilot@github.com>",
			want:    []model.AISignal{model.SignalCoAuthor},
		},
		{
			name:    "Cursor co-author",
			message: "refactor: cleanup\n\nCo-Authored-By: Cursor <cursor@cursor.com>",
			want:    []model.AISignal{model.SignalCoAuthor},
		},
		{
			name:    "Claude Code co-author",
			message: "feat: thing\n\nCo-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>",
			want:    []model.AISignal{model.SignalCoAuthor},
		},
		{
			name:    "no AI signals",
			message: "feat: manual work\n\nCo-Authored-By: John Doe <john@example.com>",
			want:    nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := aidetect.Detect(tt.author, tt.message)
			if len(got) != len(tt.want) {
				t.Errorf("Detect() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestDetectCommitMessagePatterns(t *testing.T) {
	tests := []struct {
		name    string
		message string
		want    []model.AISignal
	}{
		{
			name:    "generated by",
			message: "Generated by Claude",
			want:    []model.AISignal{model.SignalCommitMessage},
		},
		{
			name:    "ai-generated",
			message: "AI-generated code for feature X",
			want:    []model.AISignal{model.SignalCommitMessage},
		},
		{
			name:    "ai-assisted",
			message: "AI-assisted refactoring",
			want:    []model.AISignal{model.SignalCommitMessage},
		},
		{
			name:    "normal message",
			message: "feat: add login page",
			want:    nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := aidetect.Detect("", tt.message)
			if len(got) != len(tt.want) {
				t.Errorf("Detect() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestDetectBotAuthor(t *testing.T) {
	tests := []struct {
		name   string
		author string
		want   []model.AISignal
	}{
		{
			name:   "dependabot",
			author: "dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>",
			want:   []model.AISignal{model.SignalBotAuthor},
		},
		{
			name:   "renovate",
			author: "renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>",
			want:   []model.AISignal{model.SignalBotAuthor},
		},
		{
			name:   "github-actions",
			author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>",
			want:   []model.AISignal{model.SignalBotAuthor},
		},
		{
			name:   "copilot bot",
			author: "copilot-swe-agent[bot] <12345+copilot-swe-agent[bot]@users.noreply.github.com>",
			want:   []model.AISignal{model.SignalBotAuthor},
		},
		{
			name:   "human author",
			author: "Jane Doe <jane@example.com>",
			want:   nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := aidetect.Detect(tt.author, "some commit message")
			if len(got) != len(tt.want) {
				t.Errorf("Detect() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestDetectMultipleSignals(t *testing.T) {
	author := "copilot[bot] <copilot[bot]@users.noreply.github.com>"
	message := "AI-generated fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>"

	got := aidetect.Detect(author, message)
	if len(got) != 3 {
		t.Errorf("expected 3 signals, got %d: %v", len(got), got)
	}
}

func TestDetectNoDuplicateSignals(t *testing.T) {
	message := "feat: thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nCo-Authored-By: Copilot <copilot@github.com>"

	got := aidetect.Detect("", message)
	coAuthorCount := 0
	for _, s := range got {
		if s == model.SignalCoAuthor {
			coAuthorCount++
		}
	}
	if coAuthorCount != 1 {
		t.Errorf("expected 1 co-author signal, got %d", coAuthorCount)
	}
}
