package aidetect

import (
	"strings"

	"github.com/dsablic/codemium/internal/model"
)

var aiToolNames = []string{
	"claude", "copilot", "cursor", "codeium", "gemini",
	"chatgpt", "openai", "anthropic", "windsurf", "aider",
	"amazon q",
}

var aiMessagePatterns = []string{
	"generated by", "ai-generated", "ai-assisted", "auto-generated",
}

// Detect inspects a commit author and message and returns matching AI signals.
func Detect(author, message string) []model.AISignal {
	var signals []model.AISignal

	if hasCoAuthorAI(message) {
		signals = append(signals, model.SignalCoAuthor)
	}

	if hasAIMessagePattern(message) {
		signals = append(signals, model.SignalCommitMessage)
	}

	if isBotAuthor(author) {
		signals = append(signals, model.SignalBotAuthor)
	}

	return signals
}

func hasCoAuthorAI(message string) bool {
	lower := strings.ToLower(message)
	for _, line := range strings.Split(lower, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "co-authored-by:") {
			continue
		}
		for _, tool := range aiToolNames {
			if strings.Contains(line, tool) {
				return true
			}
		}
	}
	return false
}

func hasAIMessagePattern(message string) bool {
	lower := strings.ToLower(message)
	for _, pattern := range aiMessagePatterns {
		if strings.Contains(lower, pattern) {
			return true
		}
	}
	return false
}

func isBotAuthor(author string) bool {
	lower := strings.ToLower(author)
	return strings.Contains(lower, "[bot]")
}
